/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.0.0] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
STCAN_MSG TxMsg;
int seed_sent_flag=0;
int timeout_flag=0;
int seed = 0xFEEDBEEF;
int key=0;
/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnTimer_100MSEC_100( );
GCC_EXTERN void GCC_EXPORT OnBus_Connect();
GCC_EXTERN void GCC_EXPORT OnMsgID_7f8(STCAN_MSG RxMsg);
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER Function Wrapper Prototype  */
/* End BUSMASTER Function Wrapper Prototype  */


/* Start BUSMASTER generated function - OnTimer_100MSEC_100 */
void OnTimer_100MSEC_100( )
{
	TxMsg.data[0] = 0x02;
		TxMsg.data[1] = 0x27;
		TxMsg.data[2] = 0x01;
		TxMsg.data[3] = 0x00;
		TxMsg.data[4] = 0x00;
		TxMsg.data[5] = 0x00;
		TxMsg.data[6] = 0x00;
		TxMsg.data[7] = 0x00;
		SendMsg(TxMsg);
		
		
		return;

}/* End BUSMASTER generated function - OnTimer_100MSEC_100 */
/* Start BUSMASTER generated function - OnBus_Connect */
void OnBus_Connect()
{
	Trace("[Challenge designed by ETAS]");
	Trace("Bus connected");
	seed_sent_flag = 0;
	seed = 0xFEEDBEEF;
	timeout_flag=0;
	TxMsg.id = 0x7F0; 
	TxMsg.isExtended = FALSE;
	TxMsg.isRtr = FALSE;
	TxMsg.dlc = 8;
	TxMsg.cluster = 1;
}/* End BUSMASTER generated function - OnBus_Connect */
/* Start BUSMASTER generated function - OnMsgID_7f8 */
void OnMsgID_7f8(STCAN_MSG RxMsg)
{
unsigned char size = RxMsg.dlc & 0x000000FF;
char data[26];
char s[4];
int i = 0;
memset(data, 0, 26);
while (i < size) {
  memset(s, 0, 4);
  sprintf(s, "%02X ", RxMsg.data[i]);
  strcat(data, s);
  i++;
}

Trace("time: %u id: 0x%x size: %d data: %s", RxMsg.timeStamp, RxMsg.id, size, data);
if(RxMsg.data[0]==0x04 && RxMsg.data[1]==0x67 && RxMsg.data[2]==0x01 ){
	int seed = (RxMsg.data[3] * 0x100) + (RxMsg.data[4]);
	int seed2 = (seed&0xFFFF) ^ 0x0550;
	unsigned char d3 = (seed2>>8) & 0xFF;
	unsigned char d4 = (seed2>>0) & 0xFF;

TxMsg.data[0] = 0x04;
		TxMsg.data[1] = 0x27;
		TxMsg.data[2] = 0x02;
		TxMsg.data[3] = d3;
		TxMsg.data[4] = d4;
		TxMsg.data[5] = 0x00;
		TxMsg.data[6] = 0x00;
		TxMsg.data[7] = 0x00;
		SendMsg(TxMsg);	
}

}/* End BUSMASTER generated function - OnMsgID_7f8 */
